# Generated by Django 4.2.5 on 2023-10-01 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='videos/')),
                ('unique_filename', models.CharField(max_length=255)),
                ('recording_started', models.DateTimeField(blank=True, null=True)),
                ('recording_completed', models.DateTimeField(blank=True, null=True)),
                ('transcription', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='extension.transcription')),
            ],
        ),
    ]
